In [2]:
import pandas as pd

In [3]:
df=pd.read_excel('SampleData.xlsx')

In [4]:
df1 = pd.read_excel('SampleData.xlsx', sheet_name='Google Raw')
df2 = pd.read_excel('SampleData.xlsx', sheet_name='Facebook Raw')

In [5]:
df1.head()
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    180 non-null    datetime64[ns]
 1   Campaign Name           180 non-null    object
 2   Ad Set Name             180 non-null    object
 3   Cost (INR)              180 non-null    float64
 4   Impressions             180 non-null    int64
 5   Clicks (Traffic)        180 non-null    int64
 6   CTR                     180 non-null    float64
 7   CPC (INR)               180 non-null    float64
 8   Leads                   180 non-null    int64
 9   CPL (INR)               180 non-null    float64
 10  Traffic to Lead         180 non-null    float64
 11  Call                    180 non-null    int64
 12  Lead to Call            180 non-null    float64
 13  Type of Call (Online)   180 non-null    int64
 14  Type of Call (Offline)  180 non-null    int64
 15  CAC                     180 non-null    float64
dtypes: datetime64[ns](1), float64(7), int64(6), object(2)
memory usage: 22.6+ KB

,Date,Cost (INR),Impressions,Clicks (Traffic),CTR,CPC (INR),Leads,CPL (INR),Traffic to Lead,Call,Lead to Call,Type of Call (Online),Type of Call (Offline),CAC
count,180,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,2024-04-15 12:00:00,2135.868611,20448.138889,1051.755556,0.051682,2.042811,59.483333,36.316163,0.056989,29.177778,0.494670,14.611111,14.566667,76.071917
min,2024-04-01 00:00:00,1800.660000,18019.000000,900.000000,0.039535,1.543732,50.000000,26.480294,0.042662,20.000000,0.303030,10.000000,1.000000,48.949487
25%,2024-04-08 00:00:00,1966.062500,19256.000000,988.750000,0.047538,1.846401,54.000000,32.194864,0.050703,24.750000,0.405797,12.000000,10.000000,61.388465
50%,2024-04-15 12:00:00,2103.860000,20532.000000,1059.000000,0.051302,2.005577,59.000000,35.887007,0.056846,29.000000,0.487930,15.000000,15.000000,73.502695
75%,2024-04-23 00:00:00,2330.725000,21644.750000,1122.250000,0.056257,2.175921,65.000000,40.324105,0.062514,34.000000,0.553216,17.000000,19.000000,87.934102
max,2024-04-30 00:00:00,2496.100000,22967.000000,1199.000000,0.066286,2.709466,69.000000,48.718600,0.076412,39.000000,0.780000,19.000000,28.000000,118.815714
std,NaN,203.835048,1413.110487,85.994129,0.005557,0.246311,6.010675,5.358838,0.007834,5.603426,0.104663,2.844948,6.137257,16.920612

In [6]:
df2.head()
df2.info()
df2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    270 non-null    datetime64[ns]
 1   Campaign Name           270 non-null    object
 2   Ad Set Name             270 non-null    object
 3   Impressions             270 non-null    int64
 4   Clicks (Traffic)        270 non-null    int64
 5   CTR                     270 non-null    float64
 6   Cost (INR)              270 non-null    float64
 7   CPC (INR)               270 non-null    float64
 8   Leads                   270 non-null    int64
 9   CPL (INR)               270 non-null    float64
 10  Traffic to Lead         270 non-null    float64
 11  Call (Conversion)       270 non-null    int64
 12  Lead To Call            270 non-null    float64
 13  Type of Call (Online)   270 non-null    int64
 14  Type of Call (Offline)  270 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(6), object(2)
memory usage: 31.8+ KB

,Date,Impressions,Clicks (Traffic),CTR,Cost (INR),CPC (INR),Leads,CPL (INR),Traffic to Lead,Call (Conversion),Lead To Call,Type of Call (Online),Type of Call (Offline)
count,270,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000
mean,2024-04-15 12:00:00,16039.077778,802.688889,0.050286,1743.916481,2.186442,49.414815,35.430122,0.061931,19.188889,0.389412,13.80000,5.388889
min,2024-04-01 00:00:00,14031.000000,700.000000,0.039258,1500.180000,1.674397,45.000000,28.023333,0.050111,15.000000,0.277778,10.00000,0.000000
25%,2024-04-08 00:00:00,15102.750000,745.500000,0.046353,1612.315000,1.989621,47.000000,32.635068,0.057516,17.000000,0.333333,12.00000,3.000000
50%,2024-04-15 12:00:00,16067.500000,804.500000,0.050102,1750.250000,2.162740,49.000000,35.645931,0.061823,19.000000,0.391304,14.00000,5.000000
75%,2024-04-23 00:00:00,16945.250000,857.500000,0.054098,1882.950000,2.379606,52.000000,37.993202,0.066085,22.000000,0.437500,16.00000,8.000000
max,2024-04-30 00:00:00,17997.000000,899.000000,0.062968,1998.580000,2.813867,54.000000,44.043556,0.076814,24.000000,0.533333,19.00000,14.000000
std,NaN,1107.937877,61.546666,0.005207,147.806994,0.260191,2.970450,3.782106,0.006104,2.912201,0.061290,2.64308,3.518494

# Data Cleaning & Data Preparation

Identifying any missing values in the datasets.

In [7]:
def clean_and_prepare_data(df):
    # Fill missing values with mean
    df.fillna(df.mean(), inplace=True)
    # Convert date columns to datetime format
    df['Date'] = pd.to_datetime(df['Date'])
    # Remove duplicate rows
    df.drop_duplicates(inplace=True)
    # Drop unnecessary columns
    df.drop(['unnecessary_column1', 'unnecessary_column2'], axis=1, inplace=True)
    # Rename columns for consistency
    df.rename(columns={'old_column_name': 'new_column_name'}, inplace=True)
    # Handle outliers
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1
    df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]
    # Convert non-numeric values to numeric
    df = df.apply(pd.to_numeric, errors='coerce')
    # Drop rows with NaN values
    df.dropna(inplace=True)

In [8]:
# Load Google Raw data

# Display the first few rows of Google Raw data
print(df1.head())

# Perform data cleaning and preparation for Google Raw data
clean_and_prepare_data(df1)

# Display summary statistics for Google Raw data
print(df1.describe())

# Display information about Google Raw data
print(df1.info())

        Date Campaign Name Ad Set Name  Cost (INR)  Impressions  \
0 2024-04-01    Campaign A    Ad Set 1     2330.33        18714
1 2024-04-02    Campaign A    Ad Set 1     2095.18        19795
2 2024-04-03    Campaign A    Ad Set 1     2333.82        18258
3 2024-04-04    Campaign A    Ad Set 1     2487.05        22554
4 2024-04-05    Campaign A    Ad Set 1     1841.06        19872

   Clicks (Traffic)       CTR  CPC (INR)  Leads  CPL (INR)  Traffic to Lead  \
0              1061  0.056696   2.196352     51  45.692745         0.048068
1              1156  0.058399   1.812439     51  41.081961         0.044118
2              1082  0.059262   2.156950     57  40.944211         0.052680
3              1002  0.044427   2.482086     60  41.450833         0.059880
4              1078  0.054247   1.707848     54  34.093704         0.050093

   Call   Lead to Call  Type of Call (Online)  Type of Call (Offline)  \
0     27      0.529412                     17                      10
1     27      0.529412                     13                      14
2     27      0.473684                     15                      12
3     35      0.583333                     10                      25
4     37      0.685185                     10                      27

         CAC
0  86.308519
1  77.599259
2  86.437778
3  71.058571
4  49.758378

TypeError: Could not convert ['Campaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign ACampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign BCampaign B'
 'Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 1Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 2Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3Ad Set 3'] to numeric

In [11]:
# Display the first few rows of Facebook Raw data
print("\nFacebook Raw Data:")
print(df2.head())

# Perform data cleaning and preparation for Facebook Raw data
clean_and_prepare_data(df2)

# Display summary statistics for Facebook Raw data
print(df2.describe())

# Display information about Facebook Raw data
print(df2.info())

Facebook Raw Data:
        Date Campaign Name Ad Set Name  Impressions  Clicks (Traffic)  \
0 2024-04-01   Retargeting    Ad Set 5        14762               804
1 2024-04-02   Retargeting    Ad Set 5        17231               867
2 2024-04-03   Retargeting    Ad Set 5        15996               823
3 2024-04-04   Retargeting    Ad Set 5        17387               858
4 2024-04-05   Retargeting    Ad Set 5        17006               786

        CTR  Cost (INR)  CPC (INR)  Leads  CPL (INR)  Traffic to Lead  \
0  0.054464     1960.95   2.438993     53  36.999057         0.065920
1  0.050316     1623.68   1.872757     53  30.635472         0.061130
2  0.051450     1844.80   2.241555     51  36.172549         0.061968
3  0.049347     1891.43   2.204464     48  39.404792         0.055944
4  0.046219     1563.34   1.988982     51  30.653725         0.064885

   Call (Conversion)  Lead To Call  Type of Call (Online)  \
0                 23      0.433962                     12
1                 16      0.301887                     13
2                 20      0.392157                     11
3                 19      0.395833                     13
4                 18      0.352941                     16

   Type of Call (Offline)
0                      11
1                       3
2                       9
3                       6
4                       2

TypeError: Could not convert ['RetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingRetargetingOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceOpenAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudienceLookalikeAudience'
 'Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 5Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 6Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7Ad Set 7'] to numeric